//@flow
export const ACTORS_SAVE_SEARCH_RESULTS = "ACTORS_SAVE_SEARCH_RESULTS";
export const ACTORS_REMOVE_ITEM = "ACTORS_REMOVE_ITEM";
export const ACTORS_ADD_ITEM = "ACTORS_ADD_ITEM";
export const ACTORS_EDIT_ITEM = "ACTORS_EDIT_ITEM";
