//@flow
export const NAVIGATION_CHANGE_DISPLAYED_RESULTS_COUNT = "NAVIGATION_CHANGE_DISPLAYED_RESULTS_COUNT";
export const NAVIGATION_CHANGE_API_PATH = "NAVIGATION_CHANGE_API_PATH";
export const NAVIGATION_CHANGE_IS_BUSY = "NAVIGATION_CHANGE_IS_BUSY";
